[project]
name = "bank-churn-prediction"
version = "0.1.0"
description = "A bank churn prediction project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=1.0.2",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[tool.setuptools.packages.find]
include = ["src*"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
